#module load smrttools

SMRT_PYTHON_PATH_PREPEND=${FALCON_PREFIX}/bin
SMRT_PYTHON_PYTHONPATH_PREPEND=${DIR}/FALCON:${DIR}/FALCON_unzip_private:${DIR}/pypeFLOW

export SMRT_PYTHON_PATH_PREPEND
export SMRT_PYTHON_PYTHONPATH_PREPEND
